---
# Default page metadata, configures the template for all pages.
# `title` is required. `style`, `module` and `script` use any URL that responds
# with a CSS, JavaScript module or JavaScript script, respectively. Commented
# out parameters are kept as references for the template.

# rss: /rss.xml
favicon: /theme/favicon.ico
lang: en
dir: ltr
title: New website
description: A new website in cyberspace
# author:
#   - Jane Dev
# keywords:
#   - Software Engineering
toc: false
nav:
  - label: Home
    href: /index.html
# style:
#   - /assets/style.css
# module:
#   - /assets/Module.js
# script:
#   - /assets/script.js
theme:
  style:
    - /theme/style.css
    - /theme/ThemeForm.css
    - /theme/CodeHighlighter.css
  module:
    - /theme/ThemeForm.js
    - /theme/CodeHighlighter.js
    - https://esm.sh/prismjs/components/prism-bash.min.js
    - https://esm.sh/prismjs/components/prism-python.min.js
    - https://esm.sh/prismjs/components/prism-markdown.min.js
    - https://esm.sh/prismjs/components/prism-yaml.min.js
    - https://esm.sh/prismjs/plugins/toolbar/prism-toolbar.min.js
    - https://esm.sh/prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js
  # script:
  #   - /theme/script.js
---

